
APPID_STEAM = '753'
APPID_CARDS = APPID_STEAM

APP_CATEGORY_CARDS = 29

URL_COMMUNITY_BASE = 'http://steamcommunity.com'
URL_STORE_API_BASE = 'http://store.steampowered.com/api'

CURRENCY_USD = 1
CURRENCY_GBP = 2
CURRENCY_EUR = 3
CURRENCY_CHF = 4
CURRENCY_RUB = 5

CURRENCIES = {
    CURRENCY_USD: 'USD',
    CURRENCY_GBP: 'GBP',
    CURRENCY_EUR: 'EUR',
    CURRENCY_CHF: 'CHF',
    CURRENCY_RUB: 'RUB',
}
